simulation:
  nx: 512
  ny: 512
  lx: 1.0
  ly: 1.0
  cfl: 0.40
  rotations: 10
  velocity:
    type: solid_rotation
    omega: 6.283185307179586
    center_x: 0.5
    center_y: 0.5

initial_condition:
  type: zalesak
  center_x: 0.5
  center_y: 0.75
  radius: 0.18
  slot_width: 0.06
  slot_length: 0.26

scheme:
  type: weno5

output:
  enable: true
  dir: frames
  prefix: cen
  format: png
  stride: 10
  start_index: 0
  scale:
    mode: fixed
    min: 0.0
    max: 1.0
  flip_y: true
  out_w: 1000
  out_h: 1000
  interp: bilinear
  grid: true
  grid_step: 8
  grid_thick: 1
  axes: true
  colormap: turbo
  colorbar: true
