name: nbody-baseline

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build build-essential
      - name: Configure
        run: cmake -S nbody -B nbody/build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build nbody/build -j
      - name: Run baseline check
        run: python3 nbody/baseline/baseline.py check
